server:
  port: 8799

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

cloud:
  config:
    discovery:
      enabled: true
      service-id: config-server # 注册中心的服务名
    profile: dev # 指定配置文件的环境
