eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8764


spring:
  application:
    name: service-ribbon
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server  # 注册中心的服务名
      profile: dev  # 指定配置文件的环境
